
name: Run Add-On
on:
  workflow_call:
    inputs:
      timeout:
        default: 5
        required: false
        type: number
      python-version:
        default: "3.10"
        required: false
        type: string

jobs:
  Run-Add-On:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: ${{ github.event.client_payload.id }}
        run: echo run identifier ${{ github.event.client_payload.id }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run add-on
        run: python main.py '${{ toJSON(github.event.client_payload) }}'
        env:
          DC_USERNAME: ${{ secrets.DC_USERNAME }}
          DC_PASSWORD: ${{ secrets.DC_PASSWORD }}
